@host = http://localhost:5016

### 1. เพิ่ม Categories
POST {{host}}/categories
Content-Type: application/json

{ "name": "Work" }

###
POST {{host}}/categories
Content-Type: application/json

{ "name": "Study" }

### 2. เพิ่ม Tasks
POST {{host}}/tasks
Content-Type: application/json

{ "title": "Learn Minimal API", "categoryId": 1 }

###
POST {{host}}/tasks
Content-Type: application/json

{ "title": "Read a book", "categoryId": 2 }

### 3. ดู Tasks ทั้งหมด
GET {{host}}/tasks

### 4. Mark Done
PUT {{host}}/tasks/1/done

### 5. Delete
DELETE {{host}}/tasks/2

### ลบ Id ที่ไม่มี
DELETE {{host}}/tasks/999

### Mark Done Id ที่ไม่มี
PUT {{host}}/tasks/999/done

### title ว่าง
POST {{host}}/tasks
Content-Type: application/json

{ "title": "", "categoryId": 1 }

### categoryId ไม่ถูกต้อง
POST {{host}}/tasks
Content-Type: application/json

{ "title": "Test", "categoryId": 0 }

### POST task with empty title
POST {{host}}/tasks
Content-Type: application/json

{ "title": "", "categoryId": 1 }

### Mark Done Id ที่ไม่มี
PUT {{host}}/tasks/999/done

### Delete Id ที่ไม่มี
DELETE {{host}}/tasks/999

### 400 - Id ไม่ถูกต้อง
PUT {{host}}/tasks/0/done

### 404 - Id ไม่มีในระบบ
PUT {{host}}/tasks/999/done

### 204 - สำเร็จ
PUT {{host}}/tasks/1/done